import type { Metadata } from 'next'
import './globals.css'
import { Nunito } from 'next/font/google'
import Navbar from '@/app/components/Navbar/Navbar'
import RegisterModal from './components/modal/RegisterModal'
import ToasterProvider from './providers/ToasterProvider'
import LoginModal from './components/modal/LoginModal'
import getCurrenUser from './actions/getCurrentUser'

const font = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Airbnb',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children, }: { children: React.ReactNode }) {
  const currentUser = await getCurrenUser
  return (
    <html lang="en">
      <body className={font.className}>
        <ToasterProvider/>
        <Navbar currentUser = {currentUser/>
        <LoginModal/>
        <RegisterModal/>
        {children}
      </body>
    </html>
  )
}
